### ISSUE TITLE
calling pyScTransform

### ISSUE THREAD

**Issue by JBreunig** [normjam/benchmark#14]
https://github.com/theislab/scanpy/issues/1068

Thanks for creating an ScTransform wrapper!

I'm able to get it imported with no errors in Spyder but when I call it (i.e. 

> pyScTransform(adata)

), I either get a kernel error or it basically resets adata and the environment.  Can you provide an example for how to call this in a general scanpy workflow?  This in in Ubuntu and the R environment is working fine, including Seurat/ScTransform as is Python/Scanpy

Thanks in advance and sorry for my ignorance regarding r2py.

**Comment by gokceneraslan** [comment]
You can also have a look at my sctransform Python wrapper here: https://github.com/theislab/scanpy/pull/1271

**Comment by JBreunig** [comment]
I had been watching this over the past few days...I definitely will ;)

**Comment by jnmark** [comment]
> You can also have a look at my sctransform Python wrapper here: [theislab/scanpy#1271](https://github.com/theislab/scanpy/pull/1271)

Hi,

I have been trying to use this wrapper, but seems like there's some error during the conversion process:

RRuntimeError: Error in validObject(.Object) : 
  invalid class “dgCMatrix” object: 1: invalid object for slot "i" in class "dgCMatrix": got class "array", should be or extend class "integer"
invalid class “dgCMatrix” object: 2: invalid object for slot "p" in class "dgCMatrix": got class "array", should be or extend class "integer"
invalid class “dgCMatrix” object: 3: invalid object for slot "Dim" in class "dgCMatrix": got class "array", should be or extend class "integer"
invalid class “dgCMatrix” object: 4: invalid object for slot "x" in class "dgCMatrix": got class "array", should be or extend class "numeric"

Any pointers to get around this?
